export const userConstants = {
	SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
	SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',
	SIGNUP_FAILURE: 'USERS_SIGNUP_FAILURE',

	LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
	LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
	LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

	GETUSER_REQUEST: 'GETUSER_REQUEST',
	GETUSER_SUCCESS: 'GETUSER_SUCCESS',
	GETUSER_FAILURE: 'GETUSER_FAILURE',

	LOGOUT: 'USERS_LOGOUT'
};

export const movieConstants = {
	ADD_MOVIE_REQUEST: 'ADD_MOVIE_REQUEST',
	ADD_MOVIE_SUCCESS: 'ADD_MOVIE_SUCCESS',
	ADD_MOVIE_FAILURE: 'ADD_MOVIE_FAILURE',

	DELETE_MOVIE_REQUEST: 'DELETE_MOVIE_REQUEST',
	DELETE_MOVIE_SUCCESS: 'DELETE_MOVIE_SUCCESS',
	DELETE_MOVIE_FAILURE: 'DELETE_MOVIE_FAILURE',

	SEARCH_MOVIES_REQUEST: 'SEARCH_MOVIES_REQUEST',
	SEARCH_MOVIES_SUCCESS: 'SEARCH_MOVIES_SUCCESS',
	SEARCH_MOVIES_FAILURE: 'SEARCH_MOVIES_FAILURE'	
};

export const navConstants = {
	LOGIN: 'LOGIN_PAGE',
	SIGNUP: 'SIGNUP_PAGE',
	DASHBOARD: 'DASHBOARD_PAGE',
	SEARCH: 'SEARCH_PAGE',
	RESULTS: 'RESULTS_PAGE',
	NAVIGATE: 'NAVIGATE',
	ABOUT: 'ABOUT_PAGE'

}